# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
apt_packages:
  - gnupg
after_success:
  - Rscript -e 'covr::codecov()'
env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE